### ISSUE TITLE
Glowstonesearch problem

### ISSUE THREAD

**Issue by mroep** [ItziSpyder/ClickCrystals#6] opened 2023-04-16 04:09 UTC
Sometimes when you try placing the anchor it places the glowstone first

**Comment by ItziSpyder** [comment] 2023-04-16 07:23
> Sometimes when you try placing the anchor it places the glowstone first

Yes, we are aware that it does that. (The main possible cause for GlowstoneSearch module breaking might be because you were placing it on fire) The problem is that right clicking a replaceable block  (ex. fire, snow layer, grass, etc) will not trigger the PlayerInteractBlockC2SPacket. Our team is currently trying to figure out which packet is responsible for that. 

If any developer is capable for finding the corresponding packet for this scenario, you are more than welcome to help us out and submit a pull request for review!

**Comment by ItziSpyder** [comment] 2023-08-06 19:59
Thanks to @TaxEvasiqn , this issue is now patched as of version 0.9.7 or any future versions. Get it now via [Modrinth](https://modrinth.com/mod/clickcrystals/version/1.20.1-0.9.7)!

**Comment by ayaanibrahimtutla** [comment] 2023-08-14 13:04
@ItziSpyder can i close this?

**Closed** 2023-08-17 20:29 UTC
