### ISSUE TITLE
Esc crash

### ISSUE THREAD

**Issue by PoojaSagarCD99955** [ItziSpyder/ClickCrystals#49] opened 2024-01-24 11:54 UTC
How to change module crashing when pressing esc pojav

**Comment by ItziSpyder** [comment] 2024-01-24 17:00
I have been made aware of this bug already. I am terribly sorry that you had to experience this. This bug will be fixed in the next update `1.2.1`. 

As for the cause of this crash, all default keys (unset/none) are set to 256, or as you might know, the escape key. This is because that's how you escape edit mode for the setting option. Normally, Minecraft on PC would ignore the press action of this key, However, Pojav seems to be working differently.
The fact that the default unset key is escape should explain why every module is binded to that key by default. And since one of our troll modules, Silk Touch, whose sole purpose is to crash your game, is also binded to that key, PoJav players would ultimately toggle on that module their game would close.

The new default key will be set to -1. For now just rebind the key to something else for the Silk Touch module. Stay tuned for the next update on https://www.curseforge.com/minecraft/mc-mods/clickcrystals.

**Comment by I-No-oNe** [comment] 2024-01-24 22:48
@PoojaSagarCD99955 please close the issue

**Closed** 2024-01-24 23:13 UTC

**Comment by PoojaSagarCD99955** [comment] 2024-01-25 01:52
Thank Bro

**Comment by PoojaSagarCD99955** [comment] 2024-01-25 01:52
Do you play Minecraft
